
Instructional word lists were collected from six very commonly used educational resources in the United States: the Dolch word list [@Dolch1936; @Johns1970], the Fry word list [@Fry1980], Fundations from Wilson Language Basics [], the Wonders curriculum from McGraw-Hill [], the Fountas & Pinnell Comprehensive Phonics and Word Study Guide [], and the resources found in Equipped for Reading Success [@Kilpatrick2016]. These resources were selected because of their high popularity at the time of conducting the study and because they focus on the instruction of print vocabulary, emphasizing the role of common words and/or words with (a)typical structure in reading vocabulary development.

Instructional resources that teach print vocabulary vary in their organization and composition, and these six resources are no exception. Each resource makes different decisions about the words to include and their rationale for doing so. Some orient their decisions in a broader theory of reading acquisition. The six resources included in the studies here can be thought of as being different kinds of educational resources, generally speaking. Lists from @Dolch1936 and @Fry1980 are sets of useful instructional words disseminated in publications concerning reading development in education. As such they aren't instructional programs so much as reference lists identified and used by researchers and consumed by teachers as a result. The remaining four (Fundations, Wonders, Fountas & Pinnell's "Phonics, Spelling, & Word Study Guide" and Kilpatrick's "Equipped for Reading Success") are instructional _programs_ in the sense that they outline both resources to use during instruction (lists of words) and methods of instruction that can be followed in delivering these resources. These four programs vary in how formal they are as instructional tools, where on one end Wonders is a large-scale comprehensive reading curriculum and at the other end @Kilpatrick2016 represents a less formal resource, delivered only as a supplementary instructional manual lacking many of the elements of more formal programs.

### The Dolch "basic sight vocabulary"
In order to understand these resources as sources of language data, it is important to understand something about how the authors of each resource concieve of the words included and any associated instructional process related to the words. @Dolch1936 and @Fry1980 are related in how they conceive of "sight word" vocabulary. @Dolch1936 sought to summarize the important pedagogical themes related to "sight word" instruction common in educational practice of the day and publish an authoritative list of important words for the development of reading vocabulary alongside commentary about why particular words and properties of words are important for early reading instruction. Broadly speaking, Dolch believed that words should be learned if they are useful, an words are useful, generally speaking, if they are common and appear in many different (and common) contexts. As a result, many of the words in the Dolch list are conjunctions, prepositions, and pronouns. Many adverbs, adjectives, and verbs are also included so long as they were common in books at the time. For the purposes of assessing how common a given words was the author aggregated words that were morphologically related to a given uninflected form. This list included no nouns on the assumption that "each noun is tied to a special subject matter" and by definition is limited in its contextual variability. The article didn't make any assumptions about how the words should be learned other than that a student should have robust enough knowledge of the 220 words such that they all could be recognized "by sight" and that if a student couldn't perform this task, the student should continue practice on the word until they could be automatically recognized^[The use of flashcards and repetitive, rote memorization is specifically mentioned, but without any formal description or methodology associated with the learning process.].

### The Fry "Instant Words"
The original set of "Instant Words" from @Fry1957 are essentially rank-ordered frequent words in English taken from several popular word frequency lists at the time [@Dolch1936; @Rinsland1945; @Thorndike1944] supplemented with words that the author deemed common based on personal experience in the reading classroom. Quite simply, @Fry1957 provided a set of 600 frequent words organized into groups of 25 in order to allow a reading teacher access to sets of words, descreasing in frequency, of a quantity that would be easily managed in an instructional unit in the classroom. Fry's follow-up paper introduced "The New Instant Word List" [@Fry1980], 




Words and other instructional data were aggregated for each resource, which were acquired through a university library system. When identifying instructional content for each resource, teacher materials were read by a team of researchers who were supervised by a senior researcher (PhD trainee). Lists from @Dolch1936 and @Fry1980 were easily aggregated given that words from those publications already exist in table form in the public domain. The remaining four resources required more careful reading and curation by the research team. For these materials, each unit of instruction was reviewed by the team and words taught in each unit were text-transcribed in a machine-readable format, and documented in a database for analysis.

## Language data used for normative comparisons
In order to analyze instructional words with respect to their linguistic properties a number of datasets were identified and merged with the database of words aggregated for the study. One important issue concerns how instructional words compare to words children and adults tend to encounter in other language experiences - reading related and otherwise. In order to make comparisons along these lines we assembled several relevant benchmark sets using language databases that represent language experiences for different groups and in different modes of communication, both via printed and spoken language. The corpora we selected for this purpose are The Wisconsin Children's Book Corpus [WCBC; @Lewis2021], the Corpus of Contemporary American English [COCA; @Davies2011], the Child Language Data Exchange System [CHILDES; @MacWhinney2000], and words from the Educator's Word Frequency Guide from Touchstone Applied Science Associates [TASA; @Zeno1995].

The Wisconsin Children's Book Corpus contains texts commonly consumed by pre-readers (up to the age of 6). CHILDES represents language from children's spoken language environment (the data used here are from transcripts for children in the US up to the age of 6 years). TASA captures information about words in literature children are commonly exposed to in grade school, and the Corpus of Contemporary American English captures information about adult texts (in this case we aggregated words from fiction books only).

The approach to comparing the properties of instructional words to those in the benchmark datasets is as follows, and will be repeated in subsequent analyses here. For a given variable of interest, 
