---
title             : 'Which words are special? Identification of "sight" words in educational resources'
shorttitle        : "Special words"

author: 
  - name          : "Matthew J. Cooper Borkenhagen"
    corresponding : yes
    affiliation   : 1, 2
    email         : "mcooperborkenhagen@fsu.edu"
    address       : "1114 W. Call Street, Tallahassee, FL 32306"
    role:   # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Conceptualization
      - Supervision
      - Writing
      - Formal Analysis
      - Project administration
      - Data curation
  - name          : "Lauren P. Schilling"
    affiliation   : 3
    address       : "Harvard Graduate School of Education"
    role:   # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Conceptualization
      - Project administration
      - Data curation
  - name          : "Mark S. Seidenberg"
    affiliation   : 4
    role:   # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Conceptualization
      - Supervision
      - Writing
affiliation:
  - id            : 1
    institution   : "School of Teacher Education, Florida State University"
  - id            : 2
    institution   : "The Florida Center for Reading Research"
  - id            : 3
    institution   : "Harvard Graduate School of Education"
  - id            : 4
    institution   : "Department of Psychology, University of Wisconsin - Madison"

abstract: "Which words are important for early reading instruction? A standard view holds that certain words should be emphasized early in development because they are used with high frequency and/or contained atypical spelling-sound structure. Such words have been labeled “sight,” “trick,” “snap,” or simply “high frequency” words; we refer to them as “special” words. The present study examined whether instructional resources such as commonly used curricula and word lists agree on the identity of such words. We addressed this question using six such resources ranging from the classic Dolch (1937) list to modern commercial curricula. Results show substantial disagreement about the designated words and their properties.  A total of 973 distinct words are identified as special in these materials. Only 28 words (3%) appear in  all six resources, and over half appear in only a single one (560 words; 56%). Additional analyses suggest that the materials differ in their treatment of “high frequency” words and whether words exhibit consistent spelling-sound associations. Together the results indicate a surprising lack of agreement about which words should be treated as special for instructional purposes. The differences in the treatment of special words in these materials suggest that beginning readers’ learning experiences may vary greatly. In the general discussion we describe a new method for identifying special words that facilitates comparisons across curricula and clarifies the alternative bases for identifying special words. This method is based on computational theories of word reading that specify how properties of words such as spelling-sound consistency and word frequency affect learning. Such theories can provide a more systematic basis for identifying words to emphasize in early instruction."
  
keywords          : "Reading development, reading instruction, sight words"
wordcount         : "9607 words"
bibliography      : ["references.bib"]
documentclass     : "apa6"
class             : "man"
figsintext        : yes
figurelist        : no
tablelist         : yes
footnotelist      : no
lineno            : yes
replaceampersands : no
#lang              : "en-US"
output            : papaja::apa6_pdf
#output            : papaja::apa6_docx
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}[=v4.13]
  - \usepackage{array}
  - \usepackage{multirow}
  - \PassOptionsToPackage{x11names}{xcolor}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage[normalem]{ulem}
  - \usepackage{scrextend}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)


lapply(read.csv('scripts/requirements.txt', stringsAsFactors = F, header = F)[[1]], require, ch = T)
source('scripts/utilities.R')

#source('scripts/Zs.R') # replaced with structured data read (see Zs.R for specs on this object)...
Zs = read_csv("data/Zs.csv")

source_order = Zs %>% 
  group_by(source) %>% 
  summarise(source_order = first(source_order)) %>% 
  mutate(source = case_when(source == 'Fountas & Pinnell' ~ 'F&P',
                            TRUE ~ source))

source('scripts/wcbc.R')

childes = read_csv('data/childes.csv')


all_lists = read_csv('data/all_lists_v2.csv') # old call read_csv('data/all_lists.csv')
source('scripts/sets.R')


# added this coca read because it is needed in one of the sections in its raw form
source('scripts/coca.R')
source('scripts/tasa.R')

COLORS_CORPUS = c('WCBC' = 'firebrick3',
           'COCA' = 'darkslategray',
           'CHILDES' = 'gold2',
           'TASA' = 'coral')

COLORS_OTHERVAR = c('AoA' = 'darkolivegreen4',
           'Consistency' = 'turquoise3',
           'Imageability' = 'darkorange1',
           'Letters' = 'goldenrod1',
           'Syllables' = 'dodgerblue3')

COLORS_SOURCE = c('Kilpatrick' = 'darkblue',
           'Dolch' = 'darkred',
           'Fry' = 'darkorange',
           'Fundations' = 'turquoise',
           'Wonders' = 'red',
           'Fountas & Pinnell' = 'darkgreen')

```


```{r child='sections/introduction.Rmd'}

```


```{r methods, child='sections/methods.Rmd'}

```


```{r profiles_data, include=FALSE}
source('scripts/frequency_models.R')
source('scripts/lexical_models.R')
source('scripts/lexical_models_affil.R')
```


```{r overlap_data, include=FALSE}
source('scripts/overlap.R')
```


```{r properties_data, include=FALSE}
source('scripts/top_n.R')
```



```{r frequency_and_inconsistency_data, include=FALSE}

programs_by_rank_inconsistency_rank_frequency = read_csv(file = "data/programs_by_rank_inconsistency_rank_frequency.csv")

```



```{r results, child='sections/results.Rmd'}
```


```{r discussion, child='sections/discussion.Rmd'}
```


```{r appendix, child='sections/appendix.Rmd'}
```


```{r coi, child='sections/coi.Rmd'}
```

```{r backmatter, child='sections/backmatter.Rmd'}
```