
# Appendix

```{r forAppendixAOA, echo=FALSE, warning=FALSE, message=FALSE}
z_tables_lexical %>% 
  filter(var == 'aoa') %>% 
  select(-c(var, source_order)) %>% 
  apa_table(caption = 'Parameter Estimates for Source Means on Age-of-Acquisition Relative to Normative Sample from WCBC',
            note = "Bolded coefficients are statistically significant and can be interpreted as Cohen's *d* based on the statistical test performed.", escape = FALSE)

```


```{r forAppendixCONSISTENCY, echo=FALSE, warning=FALSE, message=FALSE}
z_tables_lexical %>% 
  filter(var == 'consistency') %>% 
  select(-c(var, source_order)) %>% 
  apa_table(caption = 'Consistency', escape = FALSE)

```

\newpage

```{r forAppendixIMAGEABILITY, echo=FALSE, warning=FALSE, message=FALSE}
z_tables_lexical %>% 
  filter(var == 'imageability') %>% 
  select(-c(var, source_order)) %>% 
  apa_table(caption = 'Imageability', escape = FALSE)

```


```{r forAppendixLETTERS, echo=FALSE, warning=FALSE, message=FALSE}
z_tables_lexical %>% 
  filter(var == 'letters') %>% 
  select(-c(var, source_order)) %>% 
  apa_table(caption = 'Number of Letters per Word', escape = FALSE)

```

\newpage

```{r forAppendixSYLLABLES, echo=FALSE, warning=FALSE, message=FALSE}
z_tables_lexical %>% 
  filter(var == 'syllables') %>% 
  select(-c(var, source_order)) %>% 
  apa_table(caption = 'Number of Syllables per Word', escape = FALSE)


```



```{r SourcesDesc, echo=FALSE, message=FALSE, warning=FALSE}
table_desc = all_lists %>% 
  group_by(source, word) %>% 
  summarise(childes_freq = first(childes_freq),
                    tasa_freq = first(tasa_freq),
                    wcbc_freq = first(wcbc_freq),
                    letters = first(letters),
                    syllables = first(syllables),
                    morphemes = first(morphemes)) %>% 
  ungroup() %>% 
  left_join(coca %>% 
              select(word, coca_freq = freq)) %>% 
  group_by(source) %>% 
  summarise(TASA = round(mean(tasa_freq, na.rm = T)),
            TASA_sd = round(sd(tasa_freq, na.rm = T)),
            WCBC = round(mean(wcbc_freq, na.rm = T)),
            WCBC_sd = round(sd(wcbc_freq, na.rm = T)),
            COCA = round(mean(coca_freq, na.rm = T)),
            COCA_sd = round(sd(coca_freq, na.rm = T)),
            CHILDES = round(mean(childes_freq, na.rm = T)),
            CHILDES_sd = round(sd(childes_freq, na.rm = T)),
            Letters = round(mean(letters, na.rm = T)),
            Letters_sd = round(sd(letters, na.rm = T), digits = 2),
            Syllables = round(mean(syllables, na.rm = T)),
            Syllables_sd = round(sd(syllables, na.rm = T), digits = 2)) %>% 
  mutate(TASA = str_c(TASA, " (", TASA_sd, ")"),
         WCBC = str_c(WCBC, " (", WCBC_sd, ")"),
         COCA = str_c(COCA, " (", COCA_sd, ")"),
         CHILDES = str_c(CHILDES, " (", CHILDES_sd, ")"),
         Letters = str_c(Letters, " (", Letters_sd, ")"),
         Syllables = str_c(Syllables, " (", Syllables_sd, ")")) %>% 
  select(source, TASA, WCBC, COCA, CHILDES, Letters, Syllables)
      

all_lists %>% 
  group_by(source) %>% 
  distinct(word) %>% 
  summarise(N = n()) %>%
  left_join(table_desc) %>% 
  mutate(Source = case_when(source == 'dolch' ~ 'Dolch',
                            source == 'fry' ~ 'Fry',
                            source == 'fundations' ~ 'Fundations',
                            source == 'kilpatrick' ~ 'Kilpatrick',
                            source == 'wonders' ~ 'Wonders',
                            source == 'fountas_pinnell' ~ 'Fountas & Pinnell')) %>% 
  select(-source) %>% 
  select(Source, everything()) %>% 
  apa_table(caption = "Basic Descriptive Data for All Instructional Sources",
            note = "Values for CHILDES, TASA, WCBC, and COCA are mean raw frequencies. Letters = number of letters. Syllables = number of syllables. Values in parentheses are standard deviations.")

```


Results of statistical tests for each word property against the mean in TASA.

```{r profileTableStatTest, echo=FALSE, message=FALSE, warning=FALSE}
Source = z_tables_lexical %>% filter(var == 'aoa') %>% pull(Source)
AoA = z_tables_lexical %>% filter(var == 'aoa') %>% rename(b = `\\textit{b}`, se = `\\textit{SE}`) %>% mutate(o = paste(b, ' (', se, ')', sep = '')) %>%  pull(o)
Consistency = z_tables_lexical %>% filter(var == 'consistency') %>% rename(b = `\\textit{b}`, se = `\\textit{SE}`) %>% mutate(o = paste(b, ' (', se, ')', sep = '')) %>%  pull(o)
Imageability = z_tables_lexical %>% filter(var == 'imageability') %>% rename(b = `\\textit{b}`, se = `\\textit{SE}`) %>% mutate(o = paste(b, ' (', se, ')', sep = '')) %>%  pull(o)
Letters = z_tables_lexical %>% filter(var == 'letters') %>% rename(b = `\\textit{b}`, se = `\\textit{SE}`) %>% mutate(o = paste(b, ' (', se, ')', sep = '')) %>%  pull(o)
Syllables = z_tables_lexical %>% filter(var == 'syllables') %>% rename(b = `\\textit{b}`, se = `\\textit{SE}`) %>% mutate(o = paste(b, ' (', se, ')', sep = '')) %>%  pull(o)

data.frame(cbind(Source, AoA, Consistency, Imageability, Letters, Syllables)) %>% 
  mutate(Source = case_when(Source == 'Dolch' ~ 'Dolch',
                            Source == 'Fry' ~ 'Fry',
                            Source == 'Fundations' ~ 'Fundations',
                            Source == 'Kilpatrick' ~ 'Kilpatrick',
                            Source == 'Wonders' ~ 'Wonders',
                            Source == 'Fountas_pinnell' ~ 'Fountas & Pinnell')) %>%
  apa_table(caption = 'Model Estimates for Statistical Tests of Source Means against Mean from TASA', 
            note = 'Estimates obtained from using t.test() from base R, with standard errors in parentheses. Bolded parameter estimates are statistically significant. For a full accounting of parameter estimates see appendix. Values were Z transformed on the distribution from the TASA prior to subsetting and testing by source.', escape = FALSE)
  
```



```{r top_ranked_words_by_inconsistency_frequency_top50}

rank_inconsistency_rank_frequency %>% 
  filter(word %nin% c("and")) %>% 
  filter(rank <= 50) %>%
  mutate(word = case_when(word == "i" ~ "I",
                          word == "i'm" ~ "I'm",
                          word == "i'll" ~ "I'll",
                          TRUE ~ word),
         rank = as.character(as.numeric(rank-1))) %>% 
  rename(Rank = rank, Word = word, `Dist. (Euclidean)` = distance, `Freq. (high-low)` = tasa_rank,
         `Constncy. (low-high)` = consistency_rank) %>% 
  apa_table(caption = "Top 50 Ranked Words Based Jointly on Consistency and Frequency", note = "This table extends the shorter table (top 10) provided in the text. Rankings derived from Euclidean distance of inconsistency and frequency ranking against the origin (0, 0). The calculated distance is also provided. All words for all resources were considered when making the calculation. Consistency is arranged such that a low rank means low consistency. Frequency is arranged so that a low rank means high frquency.", longtable = TRUE)

```


# References

  