# General Discussion
Words are fundamental units in language and in reading instruction. The instructional resources we have analyzed all have in common that certain words in English are prioritized for teaching, all focusing on some combination of (a) the words’ structural properties in terms of letters and sounds and (b) the words’ frequencies. There is noteworthy disagreement among programs both about which words should be included and about those properties that matter most in selecting words. Only 3% of the words across all unique words are present in all six resources (3% of words), and most words belong to a single source and no others (56% of words). Programs vary considerably in terms of the properties of the words they contain. Some select the most frequent words in print, like the Fry (1980) list, which contains words that are on average 1.69 standard deviations more frequent than the average of words from the TASA corpus. Kilpatrick, on the other hand, tends to select words that are much closer to the average frequency of words from child-directed print (.68 standard deviations in frequency).

Considerable variation is also seen for other lexical variables: age of acquisition, consistency, imageability, number of letters, and number of syllables. If educational approaches agreed on the properties of the language that matter for instruction, we would likely not see such variability across the different measures considered in the analyses here. 

We have also demonstrated a method that considers word frequency and consistency jointly, given the relevance of these two variables in selecting words for early print vocabulary. The method is explained both graphically (see Figures 8, 9, and 10) and quantitatively (see Figure 10, Table 11, and appendix). This method describes where a word fits in the frequency-consistency distribution, and measures a word's position from the extreme point in the distribution (Figure 10 and Table 11). The approach offers a reproducible method with a concrete (visual) interpretation. When comparing programs on the distribution of words using this method (Figure 11), we see additional variability. Again here, the Fry, Dolch, and Wonders lists tend toward one extreme (selecting words that are highly ranked in frequency-consistency) where Fundations and Kilpatrick tend towards the other.

## How should we assemble words for instruction?
What are the implications of these findings for research and instruction? The fact that there is little agreement about the words treated as special raises the empirical question as to whether the choice of such words have a major impact on children’s progress. Does it matter which particular special words are chosen, or is it simply that some number of them must be taught in order to get reading off the ground? At present we know of little research that directly addresses these questions. The experimental evidence on learning to read words with irregularities is limited [@Colenbrander2020]. @Colenbrander2022 found evidence that mispronunciation correction and spelling irregular words outperformed passive reading. Their study included few words during training (N = 12) and generalization outside the training items was not observed in any learning condition.

It is clear from our study and from the variation seen in instructional practice more generally that popular approaches to reading instruction vary greatly in the number of words treated as special and the amount of time allocated to teaching them. It seems unlikely that all of these methods would be equally effective, but that question requires further research. 

A broader question is whether current theories of reading and learning could be used to guide the selection of special words, the timing of when they are introduced, and the methods used in teaching them. How to accommodate the words with inconsistent, atypical, “exceptional” pronunciations is a major challenge for all phonics-based instruction. At present, the identification of such words is based on intuitions that yield highly variable results. Theories of word reading and learning may provide a more principled basis for what to teach, when, and how. In particular, theories dating from Seidenberg and McClelland (1989) do not distinguish between rule-governed words and irregular words. All words fall on a continuum of spelling-sound consistency. At one end of this continuum are highly consistent mappings (e.g., "-ist" is pronounced the same in "list", "mist", "gist", etc.), at the other the seemingly irregular words such as "pint", "none", and "does". Other words exhibit intermediate degrees of consistency.  Consistency provides a good account of numerous phenomena concerning beginning, skilled, and impaired reading [@Bolger2008; @Glushko1979; @Plaut1996; @Taylor2011; @Zevin2006]. 

This account is based in part on the observation that even the most irregular words, including ones in the resources we studied, are not arbitrary; rather, they partially overlap with other words. "Have", for example, is standardly treated as irregular because the vowel would normally be long, as in "save" and "gave"; however, "have" overlaps with neighboring words such as "hive", "hate", and "had". Treating "have" as a word to be memorized ignores the fact that what is learned about the word builds on and applies to partially overlapping words. Numerous behavioral studies have established that learning and skilled reading are affected by degrees of consistency among neighborhoods of overlapping words such as "have", "hive", "hate", "save", and "gave". Rather than learning words as arbitrary, isolated patterns, instruction could focus on teaching such words in the context of overlapping neighbors. That would be a way to reduce the number of words to be memorized, which is time consuming and a distraction from learning the many systematic correspondences between spelling and sound in English reading and spelling. 

Recent discussions among researchers and practitioners have focused on reducing the number of words that must be memorized by building such subregularities. For example, the alternative to treating "have", "give", and "love" as sight words is to build on the fact that they exhibit a pattern: the letters representing vowels are followed by "v" and "silent e". Whereas monosyllabic spoken words can end in /v/, their written forms do not end in the letter "v". Hence it could be argued that the final "e" is there to satisfy this condition, not to signal a long vowel. The child might be taught a phonics rule that covers these cases, which would allow them to “sound out” the words, obviating the need to memorize them by rote. 

Approaches such as Sounding out the sight words (ref) extend this approach to numerous words that would otherwise be candidates to be memorized by rote. The authors formulate rules that describe patterns that hold over small groups of words. Written English has innumerable subpatterns of this sort, each of which can be formulated as a teachable rule, added to the standard set of phonics rules. Research is needed to determine whether teaching such rules facilitates reading acquisition compared to other approaches. Although the intent of rules such as the one for syllable-final V and silent E is to reduce the amount of rote learning in beginning reading, it is not clear that it does so.  First, there is an additional rule to memorize, which itself requires attention, effort, and practice. Second, for the rule to be useful, the child has to learn where it does and does not apply. The rule about the E being there to avoid having the spelling end in V works for words such as HAVE and GIVE, but not the many ones like SAVE and FIVE. Learning which words the rule applies to is another type of memorization and thus not obviously easier than memorizing individual words. Given that explicit phonics instruction in many curricula is already very extensive, involving dozens of rules taught over several grades, the introduction of additional rules governed by complex conditions may not be wholly welcome.

Capitalizing on the patterns that hold among small neighborhoods of words is nonetheless an important idea. The alternative to explicitly teaching these patterns and treating them like other phonics rules is to create conditions that promote learning the patterns without having to label them. Models such as Seidenberg and McClelland’s focused on the statistical learning aspect of learning to read words. Such models illustrate how a statistical learning procedure picks up on the patterns that exist across words. The beauty of the procedure is that it does not have to be taught what the patterns are or where to look for them. It discovers the patterns in the course of learning to perform a task such as reading letter strings aloud. The model discovers patterns inherent in sets of words automatically. From this perspective the main requirement is sufficient experience with words that exhibit learnable patterns. Such models can also be used to identify efficient ways to introduce words over time: groupings that optimize learning the desired inventory of words. Rather than teaching additional rules, this approach suggests instructional activities using groups of overlapping words, drawing attention to a pattern without treating it as an explicit rule to be memorized. Words that overlap in structure support each other in learning: what is learned about HAVE is supported by neighbors such as HAD and HAS. The instructional challenge, then, is to find the ways of grouping words, including “sight words”, to promote mutually-supportive learning.

Include Set for Variability here somewhere. that stuff also makes use of the subpatterns across words. do they explicitly teach the patterns or do they do implicit learning while doing reading activities like reading aloud, or what?  

In conclusion, the finding that there is little agreement about the treatment of special words raises important questions about current instructional practices. Looking to the future, efforts might turn from identifying and explicitly teaching phonics rules and exceptions toward structuring instructional activities to promote learning statistical patterns, with explicit guidance and feedback.






In summary, we have demonstrated a number of ways in which instructional resources differ in the words they select for instruction. Our results suggest that both researchers and educators, perhaps especially curriculum authors, need to find more systematic ways to identify words for special instructional attention. Ideally words could be identified based on a model of how words are learned that shows how and why properties such as frequency and consistency, as well as imageability, and age of acquisition, among others, affect learning and skilled performance. Lacking a fully realistic model we have offered an intermediate step: choosing words based on the conjunction of two important factors, frequency and consistency.

## Limitations
Only a subset of possible programs have been selected for analysis here. Those that participated in analyses were included due to their popularity, and a more comprehensive sample could no doubt be obtained. Likewise, the programs here were selected not because they are matched perfectly with respect to their instructional priorities and methods. Future work could consider programs that report to implement more specific shared theoretical perspectives about the development of word recognition skills in order to extend these findings to approaches that are more narrowly matched.

\newpage