# Introduction

A major step in becoming a reader is being able to recognize and understand sufficient words to comprehend simple texts (ref). These include the high frequency words that occur in most texts, as well as content words such as _dinosaur_ and _skeleton_ that are “high frequency” in texts about specific topics (ref, include Adams AE article). With this level of skill, learners can be said to have achieved escape velocity: they can increase their reading skill and acquire other types of knowledge through reading itself, with decreasing reliance on external feedback. Early reading instruction focuses on these goals.

Although approaches to instruction vary, they generally assume that beginning readers will need to memorize some number of high frequency words because of the nature of written English. Many common words can be decoded (“sounded out”) using knowledge of spelling-sound correspondences (“phonics”). Explicitly teaching these correspondences is time-consuming and the sheer number of them is daunting (ref). Memorizing words is the alternative to delaying reading until sufficient spelling-sound mappings are learned. Moreover, memorization is apparently necessary for the many high frequency words that cannot be pronounced by rule because their pronunciations are irregular. A high proportion of these are words that are essential to constructing sentences (e.g., prepositions, pronouns, auxiliary verbs, determiners). 

Thus, beginning readers’ progress depends on gaining facility with common words, especially ones with atypical spelling-sound structure. Some number of words need to be memorized to jumpstart reading while knowledge of spelling-sound mappings develops. Memorization involves learning associations between the spelling of a word and its primary meaning and/or pronunciation. Historically, there have been a variety of proposals about which words should be treated this way, as well as methods of instruction. 

In a classic article, @Dolch1936 developed a list of 220 “sight words” that he thought essential for beginning readers to learn. This list (with minor updates) remains a widely-used resource. All of these words can be learned by treating them as visual patterns associated with meanings, as in the “sight word” method Dolch preferred. This approach is time-consuming because the associations between spellings and meanings are essentially arbitrary. Such associations must be explicitly taught and memorizing them requires practice. However, the list contains many words that are decodable if readers learn the relevant phonics rules (e.g., can, make, fast). Such words might then be excluded from the list of sight words in order to minimize the number that need to be memorized. 

Numerous alternatives to and modifications of the Dolch list have been proposed by scholars, most notably @Fry1957. Authors of commercial curricula have also proposed their own lists. The term “sight word” has fallen into disfavor because of its association with a discredited “whole word” approach to reading (ref); other labels such as “trick,” “snap”, and “heart” words are employed instead, all of which rely on the same basic logic. In this article, to be theory- and curriculum-neutral, we will refer to them as “special words”: ones that are identified as requiring special attention because of their importance for getting reading off the ground. Approaches differ regarding the words that are included and strategies for teaching them.

Our study examined the treatment of special words in a sample of commonly-used instructional materials (Table 1). These include popular commercial curricula (Fountas & Pinnell, Wonders, Fundations), the Dolch and Fry lists, and Kilpatrick (202x) which offers instructional guidance but is not a complete curriculum. These materials were chosen because they are in common use and therefore have a major impact on classroom instruction. We also deliberately chose materials developed at different times with differing goals and pedagogical orientations, including both commercial products and materials in the public domain. 

Our primary goal was to identify the points of convergence and divergence regarding the treatment of special words in these resources. Our study builds on previous research by Kearns and Somebody (sssr paper), who reported a lack of agreement about the definition of “sight words” in the curricula they examined. Our study considered this question in greater detail, using a broad range of instructional materials. How many words are identified as requiring special instruction, what was the basis for choosing them, and what are their properties? A high degree of convergence across resources might be predicted because of their shared focus on the highest frequency words in the language, which are easily identified. However, pressure to limit the number of words that must be memorized may result in exclusion of some of these words. In addition, the number of words that are excluded because they are treated as decodable depends on assumptions about phonics instruction. 

These empirical questions are important. A lack of agreement about such words would suggest that beginning readers’ early instructional experiences vary in ways that may affect progress, despite general agreement about the importance of focusing on high frequency words. To foreshadow the results, as Kearns and ? suggested, there is considerable variability in the treatment of special words in these resources. In the final section of this article we relate the results to current theories of word recognition and pronunciation, which provide detailed accounts of the impact of frequency and other properties of words on learning. Approaches that are more consistent with such theories are more likely to be effective.


## Old intro from here to end of introduction section:
A major step in becoming a reader is being able to recognize and understand sufficient words to comprehend simple texts (ref). These include the high frequency words that occur in most texts, as well as content words such as "dinosaur" and "skeleton" that are “high frequency” in texts about specific topics (ref, include Adams AE article). With this level of skill, learners can be said to have achieved escape velocity: they can increase their reading skill and acquire other types of knowledge through reading itself, with decreasing reliance on external feedback. Early reading instruction focuses on these goals.

Although approaches to instruction vary, they generally assume that beginning readers will need to memorize some number of high frequency words because of the nature of written English. Many common words can be decoded (“sounded out”) using knowledge of spelling-sound correspondences (“phonics”). Explicitly teaching these correspondences is time-consuming and the sheer number of them is daunting(ref). Memorizing words is the alternative to delaying reading until sufficient spelling-sound mappings are learned. Moreover, memorization is apparently necessary for the many high frequency words that cannot be pronounced by rule because their pronunciations are irregular. A high proportion of these are words that are essential to constructing sentences (e.g., prepositions, pronouns, auxiliary verbs, determiners). 

Thus, the progress of a beginning reader depends on gaining facility with common words, especially ones with atypical spelling-sound relationships. Some number of words need to be memorized to jumpstart reading while knowledge of spelling-sound mappings develops. Memorization involves learning associations between the spelling of a word and its primary meaning and/or pronunciation. Historically, there have been a variety of proposals about which words should be treated this way, as well as methods of instruction. 

In a classic article, Dolch developed a list of 220 “sight words” that he thought essential for beginning readers to learn [@Dolch1936]. This list (with minor updates) remains a widely-used resource. All of these words can be learned by treating them as visual patterns associated with meanings, as in the “sight word” method Dolch preferred. This approach is time-consuming because the associations between spellings and meanings are essentially arbitrary. Such associations must be explicitly taught and memorizing them requires practice. However, the Dolch list contains many words that are decodable if readers learn the relevant phonics rules (e.g., can, make, fast). Such words might then be excluded from the sight word inventory in order to minimize the number that need to be memorized. 

Numerous alternatives to and modifications of the Dolch list have been proposed by scholars such as @Fry1957 and more recent popular resources (e.g., readingrockets.org). Authors of commercial curricula have also proposed their own lists. The term “sight word” has fallen into disfavor because of its association with a discredited “whole word” approach to reading (ref); other labels such as “trick,” “snap”, and “heart” words are employed instead. To be theory- and curriculum-neutral, we will refer to them as “special words”, given that they are identified as requiring special attention because of their importance for getting reading off the ground. Approaches differ regarding the specific words that are included on such lists and also differ in terms of strategies for teaching them.

Our study examined the treatment of special words in a sample of commonly-used instructional materials (Table 1). These include popular commercial curricula (Fountas & Pinnell's resources, McGraw Hill's *Wonders*, Wilson Language Basics' *Fundations*), the Dolch and Fry lists [@Dolch1936; @Fry1957], and "Equipped for Reading Success" [@Kilpatrick2016] which offers instructional guidance on early reading development (but is not considered a complete curriculum). These materials were chosen because they are in common use and therefore have a major impact on classroom instruction. We also deliberately chose materials developed at different times with differing goals and pedagogical orientations, including both commercial products and materials in the public domain. 

Our primary goal was to identify the points of convergence and divergence regarding the treatment of special words in these resources. Our study builds on previous research by Kearns and Hiebert [@Kearns2022], who reported a lack of agreement about the contents in the early elementary reading curricula they examined. Our study considered this question in greater detail, using a broad range of instructional materials. How many words are identified as requiring special instruction, what was the basis for choosing them, and what are their properties? A high degree of convergence across resources might be predicted because of their shared focus on the highest frequency words in the language, which are easily identified. However, pressure to limit the number of words that must be memorized may result in exclusion of some of these words. In addition, the number of words that are excluded because they are treated as decodable depends on assumptions about phonics instruction. 

These empirical questions are important. A lack of agreement about such words would suggest that beginning readers’ early instructional experiences vary in ways that may affect progress, despite general agreement about the importance of focusing on high frequency words. To foreshadow the results, to parallel what @Kearns2022 found, there is considerable variability in the treatment of special words in these resources. In the final section of this article we relate the results to current theories of word recognition and pronunciation, which provide detailed accounts of the impact of frequency and other properties of words on learning. Approaches that are more consistent with such theories are more likely to be effective.

In this paper we investigate three questions about instructional resources aimed at teaching early reading skills. First, to what extent do programs agree on the words that are important in early reading instruction? Second, to what degree to programs align based on the properties of the words they contain? Finally, based on the properties that programs identify as important instructional words, can empirical methods be identified that allow us to _derive_ words that are important for instruction?

