# Instructional Word Corpus

In order to investigate these questions, instructional word lists were collected from six very commonly used educational resources in the United States: the Dolch word list [@Dolch1936; @Johns1970], the Fry word list [@Fry1980], Fundations from Wilson Language Basics [@Wilson2012], the Wonders curriculum from McGraw-Hill [@Wonders2017], the Fountas & Pinnell Comprehensive Phonics and Word Study Guide [@Fountas2018], and the resources found in Equipped for Reading Success [@Kilpatrick2016]. These resources were selected because of their high popularity at the time of conducting the study and because they focus on the instruction of print vocabulary, emphasizing the role of common words and/or words with (a)typical structure in reading vocabulary development.

Instructional resources that teach print vocabulary vary in their organization and composition, and these six resources are no exception. Each resource makes different decisions about the words to include and their rationale for doing so. Some orient their decisions in a broader theory of reading acquisition. The six resources included in the studies here can be thought of as being different kinds of educational resources, generally speaking. Lists from @Dolch1936 and @Fry1980 are sets of useful instructional words disseminated in publications concerning reading development in education. As such they aren't instructional programs so much as reference lists identified and used by researchers and consumed by teachers as a result. The remaining four (Fundations, Wonders, Fountas & Pinnell's "Phonics, Spelling, & Word Study Guide" and Kilpatrick's "Equipped for Reading Success") are instructional _programs_ in the sense that they outline both resources to use during instruction (lists of words) and methods of instruction that can be followed in delivering these resources. These four programs vary in how formal they are as instructional tools, where on one end Wonders is a large-scale comprehensive reading curriculum and at the other end @Kilpatrick2016 represents a less formal resource, delivered only as a supplementary instructional manual lacking many of the elements of more formal programs.

### Dolch "Basic Sight Vocabulary"
In order to understand these resources as sources of language data, it is important to understand something about how the authors of each resource concieve of the words included and any associated instructional process related to the words. @Dolch1936 and @Fry1980 are related in how they conceive of "sight word" vocabulary. @Dolch1936 sought to summarize the important pedagogical themes related to "sight word" instruction common in educational practice of the day and publish an authoritative list of important words for the development of reading vocabulary alongside commentary about why particular words and properties of words are important for early reading instruction. Broadly speaking, Dolch believed that words should be learned if they are useful, an words are useful, generally speaking, if they are common and appear in many different (and common) contexts. As a result, many of the words in the Dolch list are conjunctions, prepositions, and pronouns. Many adverbs, adjectives, and verbs are also included so long as they were common in books at the time. For the purposes of assessing how common a given words was the author aggregated words that were morphologically related to a given uninflected form. This list included no nouns on the assumption that "each noun is tied to a special subject matter" and by definition is limited in its contextual variability. The article didn't make any assumptions about how the words should be learned other than that a student should have robust enough knowledge of the 220 words such that they all could be recognized "by sight" and that if a student couldn't perform this task, the student should continue practice on the word until they could be automatically recognized^[The use of flashcards and repetitive, rote memorization is specifically mentioned, but without any formal description or methodology associated with the learning process.].

### Fry "Instant Words"
The original set of "Instant Words" from @Fry1957 are essentially rank-ordered frequent words in English taken from several popular word frequency lists at the time [@Dolch1936; @Rinsland1945; @Thorndike1944] supplemented with words that the author deemed common based on personal experience in the reading classroom. Quite simply, @Fry1957 provided a set of 600 frequent words organized into groups of 25 in order to allow a reading teacher access to sets of words, decreasing in frequency, of a quantity that would be easily managed in an instructional unit in the classroom. Fry's follow-up paper introduced "The New Instant Word List" [@Fry1980], a revised version of the earlier set published over 20 years prior and also building off the related list published in @Sakiey1979. The 1980 list included fewer words (300 total), designed with the same logic as the list published in 1957 but with new frequency counts used as selection criteria.

### Wilson's Fundations "Trick Words"
The Fundations curriculum summarizes their approach to common words that often contain atypical structure as follows: High-frequency words need to be learned in such a way that they can be read (or spelled) quickly, regardless of their letter-sound structure. The program also identifies that many common words contain "irregular, non-phonetic words that do not follow the 'system' of the language". As a result, these words must be memorized and are labeled "trick words", and students are taught specifically that these words should not be decomposed based on their phonemic structure (they should not be "tapped out")^[Note that while words introduced to students in this way are not learned using the system of letters and sounds in English and thus are not "tapped out", when taught to spell these words students are taught about the portion(s) of the words that do not cohere with the "system". For example, for the word "said", the "-aid" portion would be identified as irregular, standing in contrast to the phonic rules that would otherwise indicate that the word rhyme with "PAID".]. More explicitly, students are taught that these words contain exceptional structure, and the distinction between "high-frequency" and "phonetically irregular" isn't made directly in the classroom. Rather, students are told that these words "do not follow the 'system' of the language...[they] are phonetically irregular".


### Fountas & Pinnell's "Words to Know"
Special words in Fountas & Pinnell's materials are taught exclusively with regard to their status as high-frequency words. Common words of this kind are taught regularly throughout the elementary grades in the program, with specific instructional routines devoted to them. More specifically, these words are identified as important to reading success (labeled "words to know" in their materials) precisely because they are encountered often in print, and this property is referenced explicitly when teaching. For example, students are told that "You see some words many times when you read. You need to learn words that you see many times because they help you read and write." (Grade 3; p. 34) However, their structural properties are treated only as incidental; the words aren't described as exceptional, as a general property, however if a given word on this list contains exceptional structure it can be pointed out by the teacher or the student. The identification of exceptional structure isn't a central aspect of what is taught to the student, and it isn't required content in the program. For example, for the word "because", a range of different possible discussion points are mentioned. These include discussing with the students that the word resembles "before" and "become", or that the word "has a silent _e_ at the end". Furthermore, outside of explaining to students that many words need to be known because they are common, instruction about these words is often oriented towards the student making observations about the words themselves, rather than the teacher dictating to the student the structural properties that make the word interesting, useful, or exceptional in some way.

### McGraw-Hill's Wonders High-Frequency Words
The Wonders curriculum describes special words in a way that is similar to Wilson's Fundations: there is a set of very common words that must be prioritized in instruction, and many of these words contain atypical structure and "cannot be decoded" (Grade 1; p. S7). Students are taught to read the word (including in context), spell the word aloud, and write it. The list of high-frequency words that students are exposed to throughout the year is organized based on structural properties the words contain, namely that words that contain the same spelling patterns are organized together in the list of words (organized in a visual resource of some kind, determined by the teacher), though these patterns aren't explicitly identified in the curricular materials. In general, these words are memorized using the routine that involves reading, spelling, and writing the words, though teachers are instructed to identify letter-sound structure the words contain as needed despite the structure itself not being specified in the teacher's manual.

### Kilpatrick's "Irregular Words"
The "irregular words" in Kilpatrick's (2016) materials are taught on the basis that they violate the "grapho-phoneme regularities of printed English", and it is noted in the book that these words tend include many common words. The instructional materials (Appendix I) specify a set of words that comprise "over 300 of the most common irregular words to use for this activity" (p. 64). The list includes many of the Dolch wordlist, and the author states that students should be able to spell the Dolch words (included in the Appendix) correctly before moving on to the remainder of the words included. The primary technique provided for teaching these words is mnemonic: irregular words should be taught using an alternative spelling that conforms to a possible sequence of letters should the word be spelled in a more predictable fashion, and students should also be presented with the alternative pronunciation based on this alternative spelling. One example provided is "Wednesday", which should be taught with the alternative spelling of "wed-ness-day", and the associated most likely pronunciation based on that spelling^[It is noted in the text that not all irregular words permit this approach. A few examples are given for the alternative spelling/ pronunciation; an exhaustive list to support this type of instruction is not provided.]. So, as a result, the program has elements of memorization in their approach to special words, though instruction does include learning about specific segments of words that seem to violate expectations about the letter-sound relationships in English.

An additional explanation in the materials points to the utility of identifying the "irregular letter/sound connection" in an irregular word (p. 58). The author notes that irregular words are most often so because of one small segment in the word comprising the irregularity. The examples provided in the text are the AI in SAID and the S in ISLAND. Correspondingly, learning can be enhanced by focusing the child's attention on the portion of the word other than the irregularity, which the author refers to as the "phonological framework". The child then will "use the normally performing letter-sound combinations to 'anchor' [the] irregular word in memory." The teacher's job, then, is to "point out the regular elements within all words". While these segments are not exhaustively identified by the manual, the word list given in the appendix provides example words to use during instruction. Nonetheless, the critical detail to keep in mind for this instructional resource is that words are included because of their atypical structure, first and foremost. The instructional approach involves identifying the regular structure of these words support learning and subsequent retrieval. Their status as common words is secondary, but also noted.

## Data aggregation
Words and other instructional data were aggregated for each resource, which were acquired through a university library system. When identifying instructional content for each resource, teacher materials were read by a team of researchers who were supervised by a senior researcher (the 1st author). Lists from @Dolch1936 and @Fry1980 were easily aggregated given that words from those publications already exist in table form in the public domain. The remaining four resources required more careful curation by the research team. For these materials, each unit of instruction was reviewed by the team and words taught in each unit were text-transcribed in a machine-readable format, and documented in a database for analysis. Words in following the curriculum descriptions above were used to identify subsets within each program for analysis given that each of the four other programs teach additional content (beyond those identified here). The resulting list is comprised of `r length(unique(all_lists$word))` unique words, and `r nrow(all_lists)` total words.
