---
title             : 'SUPPLEMENT: Which words are special? Identification of "sight" words in educational resources'
shorttitle        : "SUPPLEMENT: Special words"


abstract: "---"
  
keywords          : "Reading development, reading instruction, sight words"
documentclass     : "apa6"
class             : "man"
figsintext        : yes
figurelist        : no
tablelist         : yes
footnotelist      : no
lineno            : yes
replaceampersands : no
#lang              : "en-US"
output            : papaja::apa6_pdf
#output            : papaja::apa6_docx
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}[=v4.13]
  - \usepackage{array}
  - \usepackage{multirow}
  - \PassOptionsToPackage{x11names}{xcolor}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage[normalem]{ulem}
  - \usepackage{scrextend}
  - \usepackage{caption}
  - \captionsetup{font=small}
  - \usepackage{lipsum}
  - \usepackage{setspace}
  - \usepackage{fancyhdr}
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)


lapply(read.csv('scripts/requirements.txt', stringsAsFactors = F, header = F)[[1]], require, ch = T)
source('scripts/utilities.R')

#source('scripts/Zs.R') # replaced with structured data read (see Zs.R for specs on this object)...
Zs = read_csv("data/Zs.csv")

source_order = Zs %>% 
  group_by(source) %>% 
  summarise(source_order = first(source_order)) %>% 
  mutate(source = case_when(source == 'Fountas & Pinnell' ~ 'F&P',
                            TRUE ~ source))

source('scripts/wcbc.R')

childes = read_csv('data/childes.csv')


all_lists = read_csv('data/all_lists_v2.csv') # old call read_csv('data/all_lists.csv')
source('scripts/sets.R')


# added this coca read because it is needed in one of the sections in its raw form
source('scripts/coca.R')
source('scripts/tasa.R')

COLORS_CORPUS = c('WCBC' = 'firebrick3',
           'COCA' = 'darkslategray',
           'CHILDES' = 'gold2',
           'TASA' = 'coral')

COLORS_OTHERVAR = c('AoA' = 'darkolivegreen4',
           'Consistency' = 'turquoise3',
           'Imageability' = 'darkorange1',
           'Letters' = 'goldenrod1',
           'Syllables' = 'dodgerblue3')

COLORS_SOURCE = c('Kilpatrick' = 'darkblue',
           'Dolch' = 'darkred',
           'Fry' = 'darkorange',
           'Fundations' = 'turquoise',
           'Wonders' = 'red',
           'Fountas & Pinnell' = 'darkgreen',
           'FP' = 'darkgreen')

```



```{r profiles_data, include=FALSE}
source('scripts/frequency_models.R')
source('scripts/lexical_models.R')
source('scripts/lexical_models_affil.R')
```



```{r overlap_data, include=FALSE}
source('scripts/overlap.R')
```


```{r properties_data, include=FALSE}
source('scripts/top_n.R')
```



```{r frequency_and_inconsistency_data, include=FALSE}

programs_by_rank_inconsistency_rank_frequency = read_csv(file = "data/programs_by_rank_inconsistency_rank_frequency.csv")

```


## Supplement to Table 4: All Words that Appear in Only a Single Resource

```{r supplement_1}
all_lists %>% 
  group_by(source, word) %>% 
  summarise(word = first(word)) %>% 
  ungroup() %>% 
  group_by(word) %>% 
  summarise(count = n()) %>% 
  filter(count == 1) %>% 
  left_join(wcbc) %>% 
  select(word, wcbc_rank) %>%
  arrange(-desc(wcbc_rank)) %>%
  mutate(wcbc_rank = as.character(wcbc_rank),
         wcbc_rank = case_when(is.na(wcbc_rank) ~ "NP",
                               TRUE ~ wcbc_rank)) %>%
  mutate(final = str_c(word, ' (', wcbc_rank, ')')) %>%
  select(final) %>% 
  pull(final) %>% 
  matrix(ncol = 5) %>% 
  apa_table(caption = 'All Words that Appear in Only a Single Resource', note = 'Rank frequency taken from the TASA is given in parentheses. Words that are not present in that corpus are marked with “NP” (“not present”), indicating that they are very infrequent in texts written for children.', col.names = NULL)
  
```



## Supplement to Figure 2

```{r}

counts_by_source = all_lists %>% 
  group_by(source) %>% 
  distinct(word) %>% 
  left_join(all_lists %>% 
              group_by(source) %>% 
              distinct(word) %>% 
              ungroup() %>% 
              group_by(word) %>% 
              summarise(count = n()) %>% 
              ungroup()) %>% 
  ungroup() %>% 
  group_by(source, count) %>% 
  summarise(counts = n()) %>% 
  left_join(all_lists %>% 
              group_by(source) %>% 
              distinct(word) %>% 
              summarise(n = n()) %>% 
              ungroup()) %>% 
  mutate(prop = round(counts/n, digits = 2)) %>% 
  ungroup() %>% 
  mutate(source = case_when(source == 'dolch' ~ 'Dolch',
                            source == 'fry' ~ 'Fry',
                            source == 'fundations' ~ 'Fundations',
                            source == 'wonders' ~ 'Wonders',
                            source == 'fountas_pinnell' ~ 'Fountas & Pinnell')) %>%
  apa_table(caption = 'Supplement to Figure 2, Panel A in paper. For all six resources the proportion of words that occur in 1-6 of the resources are provided.', col.names = c("Source", "Count", "Words per count", "Words in source", "Prop."))

```


```{r}

counts_by_source_without_kilpatrick = all_lists %>% 
  filter(source != "kilpatrick") %>% 
  group_by(source) %>% 
  distinct(word) %>% 
  left_join(all_lists %>% 
              filter(source != "kilpatrick") %>% 
              group_by(source) %>% 
              distinct(word) %>% 
              ungroup() %>% 
              group_by(word) %>% 
              summarise(count = n()) %>% 
              ungroup()) %>% 
  ungroup() %>% 
  group_by(source, count) %>% 
  summarise(counts = n()) %>% 
  left_join(all_lists %>% 
              filter(source != "kilpatrick") %>% 
              group_by(source) %>% 
              distinct(word) %>% 
              summarise(n = n()) %>% 
              ungroup()) %>% 
  mutate(prop = round(counts/n, digits = 2)) %>% 
  ungroup() %>% 
  mutate(source = case_when(source == 'dolch' ~ 'Dolch',
                            source == 'fry' ~ 'Fry',
                            source == 'fundations' ~ 'Fundations',
                            source == 'wonders' ~ 'Wonders',
                            source == 'fountas_pinnell' ~ 'Fountas & Pinnell')) %>% view()
  apa_table(caption = 'Supplement to Figure 2, Panel B in paper. For all resources except for Kilpatrick the proportion of words that occur in 1-6 of the resources are provided.', col.names = c("Source", "Count", "Words per count", "Words in source", "Prop."))


```

